import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const FontInter = Inter({
//   variable: "--font-Inter",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Root",
  description: "Generated by create next app",
};
// ${geistSans.variable} ${geistMono.variable}${FontInter.variable}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="w-full mx-auto text-center py-4 text-2xl text-white bg-gray-800">
          <h1>header</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
