import type { Metadata } from "next";
import "./globals.css";
import { useContext } from "react";
import { Sun, Moon, Menu, X } from "lucide-react";
import { ThemeContext } from "../context/ThemeContext";
import "../../fontawesome-free-5.15.4-web/css/all.min.css";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ${geistSans.variable} ${geistMono.variable}

export default function RootLayout({ children }: LayoutProps<"/">) {
  const navItems = [
    { href: "#home", label: "Home" },
    { href: "#about", label: "About" },
    { href: "#projects", label: "Projects" },
    { href: "#contact", label: "Contact" },
  ];
  const navLinks = [
    { href: "#home", label: "Home" },
    { href: "#about", label: "About" },
    { href: "#projects", label: "Projects" },
    { href: "#contact", label: "Contact" },
  ];
  const { theme, toggleTheme } = useContext(ThemeContext);
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const socialLinks = [
    {
      name: "GitHub",
      href: "https://github.com/mohammadmohammadi785-crypto",
      icon: <i className="h-5 fab fa-github w-5 sm:h-6 sm:w-6" />,
    },
    {
      name: "LinkedIn",
      href: "https://www.linkedin.com/in/mohammad-mohammadi-372a45394/",
      icon: <i className="h-5 fab fa-linkedin w-5 sm:h-6 sm:w-6"></i>,
    },
    {
      name: "Twitter",
      href: "https://x.com/M0HAMMADI1212",
      icon: <i className="h-5 fab fa-twitter w-5 sm:h-6 sm:w-6"></i>,
    },
  ];

  const toggleMenu = () => setIsMenuOpen(!isMenuOpen);
  const contactInfo = [
    {
      label: "Email",
      value: "mohammadmohammadi2025@gmail.com",
      icon: <i className="h-5 w-5 fas fa-mail-bulk sm:h-6 sm:w-6 mr-2"></i>,
    },
    {
      label: "Phone",
      value: "+93 729125123",
      icon: <i className="h-5 w-5 fas fa-phone sm:h-6 sm:w-6 mr-2"></i>,
    },
  ];
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="bg-black border-b-normal border-b text-white py-3 sm:py-4 sticky top-0 z-50 shadow-lg">
          <div className="container mx-auto px-4 flex justify-between items-center">
            <h1 className="text-xl brush gradient-bg text-normal sm:text-2xl md:text-3xl font-extrabold tracking-tight">
              Mohammad Mohammadi
            </h1>
            <div className="hidden sm:flex items-center space-x-6">
              <nav>
                <ul className="flex space-x-6 md:space-x-8">
                  {navItems.map((item) => (
                    <li key={item.href}>
                      <a
                        href={item.href}
                        className="flex text-normal items-center transition-colors"
                      >
                        <span className="hidden md:inline ml-1">
                          {item.label}
                        </span>
                      </a>
                    </li>
                  ))}
                </ul>
              </nav>
              <button
                onClick={toggleTheme}
                className="p-2 text-normal rounded-full"
              >
                {theme === "light" ? (
                  <Moon className="h-5 w-5" />
                ) : (
                  <Sun className="h-5 w-5" />
                )}
              </button>
            </div>
            <div className="flex items-center space-x-3 sm:hidden">
              <button
                onClick={toggleTheme}
                className="p-2 rounded-full bg-black"
              >
                {theme === "light" ? (
                  <Moon className="h-5 w-5" />
                ) : (
                  <Sun className="h-5 w-5" />
                )}
              </button>
              <button onClick={toggleMenu} className="p-2">
                {isMenuOpen ? (
                  <X className="h-6 w-6" />
                ) : (
                  <Menu className="h-6 w-6" />
                )}
              </button>
            </div>
          </div>
          {isMenuOpen && (
            <nav className="sm:hidden fixed top-0 right-0 h-full w-64 bg-black z-40 shadow-2xl">
              <div className="flex justify-end p-4">
                <button onClick={toggleMenu}>
                  <X className="h-7 w-7" />
                </button>
              </div>
              <ul className="flex flex-col space-y-6 px-6 pt-4">
                {navItems.map((item) => (
                  <li key={item.href}>
                    <a
                      href={item.href}
                      onClick={toggleMenu}
                      className="flex items-center text-lg text-normal transition-colors"
                    >
                      <span className="ml-3">{item.label}</span>
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          )}
        </header>
        <div className="max-w-7xl mx-auto">{children}</div>
        <footer className="bg-black border-t text-white py-8 sm:py-12">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 sm:gap-8">
              <div>
                <h3 className="text-base sm:text-lg font-semibold mb-4 text-normal">
                  Navigation
                </h3>
                <ul className="space-y-2">
                  {navLinks.map((link) => (
                    <li key={link.href}>
                      <a
                        href={link.href}
                        className="text-normal transition-colors text-sm sm:text-base"
                      >
                        {link.label}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <h3 className="text-base sm:text-lg font-semibold mb-4 text-normal">
                  Follow Me
                </h3>
                <div className="flex text-normal flex-col">
                  {socialLinks.map((link) => (
                    <a
                      key={link.name}
                      href={link.href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-normal flex flex-row w-fit my-2.5"
                    >
                      {link.icon}
                      {link.name}
                    </a>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="text-base sm:text-lg font-semibold mb-4 text-normal">
                  Contact Info
                </h3>
                <ul className="space-y-2">
                  {contactInfo.map((info) => (
                    <li
                      key={info.label}
                      className="flex items-center text-normal text-sm sm:text-base"
                    >
                      {info.icon}
                      {info.value}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
